apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    # pod metadata and spec
    metadata:
      labels:
        app: auth
    spec:
      containers:
        - name: auth
          image: moremar/kub-network-auth:latest