apiVersion: apps/v1
kind: Deployment
metadata:
  name: tasks-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tasks
  template:
    # pod metadata and spec
    metadata:
      labels:
        app: tasks
    spec:
      containers:
        - name: tasks
          image: moremar/kub-network-tasks:latest
          env:
            # set the AUTH_HOST env var to the domain name of the auth service
            - name: AUTH_HOST
              value: auth-service.default
            - name: TASKS_FOLDER
              value: tasks