# build stage to generate production code
FROM    node:14-alpine as build_stage
WORKDIR /app
COPY    package.json .
RUN     npm install
COPY    . .
RUN     npm run build

# deploy stage to start a web server serving production code
# the built code is copied to /usr/share/nginx/html in NGINX (default served folder)
FROM    nginx:stable-alpine
COPY    --from=build_stage /app/build /usr/share/nginx/html
EXPOSE  80
CMD     ["nginx", "-g", "daemon off;"]